### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by AlexisPotvin** [Parrot-Developers/sequoia-ptpy#5] opened 2016-10-18 20:43 UTC
Is there any package installation other then pip install . or python setup.py install?
Because i keep having Import Error for package 
LengthValueAdapter
BitField

**Comment by domenzain** [comment] 2016-10-19 09:39
Those have disappeared in the latest Construct with a rethought API.
I think it's best to adapt to that.

In the meantime you can change the `requirements.txt` line for construct to `construct==2.5.2` or `construct<2.5.5`.

**Comment by domenzain** [comment] 2016-11-02 16:16
#7 is a duplicate of this same bug.

**Comment by domenzain** [comment] 2016-11-04 18:42
This is resolved with the migration.

**Closed** 2016-11-04 18:42 UTC
Labels: bug

**Comment by jcea** [comment] 2016-12-13 00:50
Hitting this. We need a new PYPI release :-)
